export const DEPARTMENT_CONFIG_GETALL_SUCCESS = "DEPARTMENT_CONFIG_GETALL_SUCCESS";
export const DEPARTMENT_CONFIG_CREATE_SUCCESS = "DEPARTMENT_CONFIG_CREATE_SUCCESS";
export const DEPARTMENT_CONFIG_UPDATE_SUCCESS = "DEPARTMENT_CONFIG_UPDATE_SUCCESS";
export const DEPARTMENT_CONFIG_DELETE_SUCCESS = "DEPARTMENT_CONFIG_DELETE_SUCCESS";