export const REQUESTOTP_SUCCESS="REQUESTOTP_SUCCESS";
export const REQUESTOTP_FAIL="REQUESTOTP_FAIL";

export const VALIDATEOTP_SUCCESS="VALIDATEOTP_SUCCESS";
export const VALIDATEOTP_FAIL="VALIDATEOTP_FAIL";