export const PRIORITY_FETCH_SUCESS = "PRIORITY_FETCH_SUCESS";
export const PRIORITY_FETCH_FAIL = "PRIORITY_FETCH_FAIL";
export const PRIORITY_DELETE_SUCCESS="PRIORITY_DELETE_SUCCESS";
export const PRIORITY_DELETE_FAIL="PRIORITY_DELETE_FAIL"
export const PRIORITY_CREATE_SUCCESS = "PRIORITY_CREATE_SUCCESS";
export const PRIORITY_CREATE_FAIL = "PRIORITY_CREATE_FAIL";
export const PRIORITY_UPDATE_SUCCESS = "PRIORITY_UPDATE_SUCCESS";
export const PRIORITY_UPDATE_FAIL = "PRIORITY_UPDATE_FAIL";

