export const ROSTER_MANAGEMENT_GETALL_SUCCESS = "ROSTER_MANAGEMENT_GETALL_SUCCESS";
export const ROSTER_MANAGEMENT_CREATE_SUCCESS = "ROSTER_MANAGEMENT_CREATE_SUCCESS";
export const ROSTER_MANAGEMENT_UPDATE_SUCCESS = "ROSTER_MANAGEMENT_UPDATE_SUCCESS";
export const ROSTER_MANAGEMENT_DELETE_SUCCESS = "ROSTER_MANAGEMENT_DELETE_SUCCESS";


export const WORKER_LIST_GETALL = "WORKER_LIST_GETALL";