export const USERGROUP_FETCH_SUCCESS = "USERGROUP_FETCH_SUCCESS";
export const USERGROUP_FETCH_FAIL = "USERGROUP_FETCH_FAIL";

export const USERGROUP_POST_SUCCESS = "USERGROUP_POST_SUCCESS";
export const USERGROUP_POST_FAIL = "USERGROUP_POST_FAIL";

export const USERGROUP_EDIT_SUCCESS = "USERGROUP_EDIT_SUCCESS";
export const USERGROUP_EDIT_FAIL = "USERGROUP_EDIT_FAIL";

export const USERGROUP_DELETE_SUCCESS = "USERGROUP_DELETE_SUCCESS";
export const USERGROUP_DELETE_FAIL = "USERGROUP_DELETE_FAIL";

export const APPLICATION_MENU_FETCH_SUCCESS = "APPLICATION_MENU_FETCH_SUCCESS";
export const APPLICATION_MENU_FETCH_FAIL = "APPLICATION_MENU_FETCH_FAIL"